### ISSUE TITLE
Easy to become confused with all the definitions

### ISSUE THREAD

**Issue by Swiftnesses** [SergeRegoor/nl.regoor.statecontrol#5]
Great app, it just took me a while to get my head around it :)

Perhaps you could look to simplify the logic, or at least the definitions? It's quite daunting at first!

For example "follow-up state" to me is "Change state to", and "follow-up action" is "Trigger action". Okay, these are not perfect, but perhaps we can simplify the language a little.

Given the usage, it might also be beneficial to consider a nice indicator to clearly show triggers and actions. Love the app though, great work!

**Comment by SergeRegoor** [comment]
Thanks for your feedback! I agree, it's not an easy app to grasp. Maybe a little too abstract for most to understand. But very flexible, and that comes at a cost.

Indeed changing definitions could be a good one. I try not to use "trigger" as a definition, because it's also used in Homey's interface, so that could be confusing. I'll think about other definitions, and post back here once I thought of something. 

Do you mean indicators in the flow editor, or on the settings page?

**Comment by SergeRegoor** [comment]
Your feedback has been very helpful. I've just submitted v0.2.1 to the app store, which is in fact a totally rewritten app. Terminology is different, and a lot of changes to create some structure.
